### PR TITLE
fix: use tostring to match url

### LINKED ISSUE #63: Using Ruleset 2.0.0 receive scope.sandbox.value.match is not a function
## Context
Migrating from the rule set 1.4.3 to 2.0.0, I have now the following error
`scope.sandbox.value.match is not a function`

while calling :

```bash
spectral lint  openapi-test.json
```

content of `.spectral.json
```json
{
  "extends":["spectral:oas","spectral:asyncapi", "owasp.ts"]
}
```

`owasp.ts` contains 
- https://unpkg.com/browse/@stoplight/spectral-owasp-ruleset@1.4.3/dist/ruleset.mjs
- or https://unpkg.com/browse/@stoplight/spectral-owasp-ruleset@2.0.0/dist/ruleset.mjs

## Current Behavior
crash with scope.sandbox.value.match is not a function

## Expected Behavior

Prints the findings

## Steps to Reproduce

1. take this spec 
```json
{
  "openapi": "3.0.1",
  "info": {
    "contact": {
      "email": "TODO@todo.com"
    },
    "title": "todo",
    "description": "TODO",
    "version": "0.0.0"
  },
  "servers": [
    {
      "url": "https://localhost:8000",
      "description": "Local development"
    }
  ],
  "tags": [
    {
      "name": "service-state"
    }
  ],
  "paths": {
    "/readiness": {
      "get": {
        "description": "Check the readiness of the service (internally used by k8s)",
        "operationId": "getReadiness",
        "tags": [
          "service-state"
        ],
        "security": [],
        "responses": {
          "200": {
            "description": "The service is healthy",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/serviceReadiness"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "serviceReadiness": {
        "type": "object",
        "description": "represents the data structure to answer to the /readiness enpoint ",
        "additionalProperties": false,
        "properties": {
          "status": {
            "$ref": "#/components/schemas/binaryStatus"
          },
          "message": {
            "type": "string",
            "pattern": "^[\\x00-\\x7F]*$",
            "maxLength": 140,
            "default": "Service is ready to accept requests"
          },
          "dependencies": {
            "type": "array",
            "description": "list of serviceDependency ",
            "maxItems": 20,
            "items": {
              "$ref": "#/components/schemas/serviceDependency"
            }
          }
        },
        "required": [
          "status",
          "message",
          "dependencies"
        ]
      },
      "binaryStatus": {
        "type": "string",
        "description": "status",
        "enum": [
          "ok",
          "not okay"
        ]
      },
      "serviceDependency": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "status": {
            "$ref": "#/components/schemas/binaryStatus"
          },
          "name": {
            "type": "string",
            "pattern": "^[\\x00-\\x7F]{0,50}$",
            "description": "dependency name",
            "maxLength": 50,
            "minLength": 0,
            "example": "my  broker"
          }
        }
      }
    },
    "responses": {},
    "parameters": {}
  }
}
```
3. spectral lint  openapi-test.json -> failed
4. remove properties of serviceDependency
5.  spectral lint  openapi-test.json -> went through

## Environment

- Version used: 
- spectral cli 6.11.0
- Environment name and version (e.g. Chrome 39, node.js 5.4): n.a
- Operating System and version (desktop or mobile): Debian 11
- Link to your environment/workspace/project:

### PR DESCRIPTION
**Pull request by mnaumanali94**
Fixes #63

### CODE REVIEW

**Review by frankkilcommins — APPROVED** [review]
LGTM - should we have a test to cover each of these type `given` scenarios (future issue to harden test suite perhaps)

**Review by P0lip — COMMENTED** [review]
How about this?

```diff
Subject: [PATCH] fix: tweak api7:2023-concerning-url-parameter
---
Index: src/ruleset.ts
<+>UTF-8
===================================================================
diff --git a/src/ruleset.ts b/src/ruleset.ts
--- a/src/ruleset.ts	(revision d233da88b881d1486cc9aa762b77c99d2e44e47b)
+++ b/src/ruleset.ts	(date 1710170011929)
@@ -1,6 +1,5 @@
 import {
   defined,
-  undefined,
   truthy,
   pattern,
   schema,
@@ -16,6 +15,9 @@
   formats: [oas2, oas3],
 
   aliases: {
+    PathItem: ['$.paths[*]'],
+    OperationObject: ['#PathItem[get,put,post,delete,options,head,patch,trace]'],
+
     ArrayProperties: {
       targets: [
         {
@@ -716,10 +718,15 @@
       description:
         "Using external resource based on user input for webhooks, file fetching from URLs, custom SSO, URL previews, or redirects, can lead to a wide variety of security issues.\n\nLearn more about Server Side Request Forgery here: https://owasp.org/API-Security/editions/2023/en/0xa7-server-side-request-forgery/",
       severity: DiagnosticSeverity.Information,
-      given:
-        '$.paths..parameters[*][?(@property === "name" && (@ === "callback" || @ === "redirect" || @.match(/(_url|Url|-url)$/)))]^',
+      given: [
+        '#PathItem.parameters[*].name',
+        '#OperationObject.parameters[*].name',
+      ],
       then: {
-        function: undefined,
+        function: pattern,
+        functionOptions: {
+          notMatch: /(^(callback|redirect)|(_url|Url|-url))$/,
+        }
       },
     },
```

File: src/ruleset.ts [hunk 1]
```diff
@@ -716,10 +715,15 @@ export default {
...
-      given:
-        '$.paths..parameters[*][?(@property === "name" && (@ === "callback" || @ === "redirect" || @.match(/(_url|Url|-url)$/)))]^',
+      given: [
+          '$.paths[*].parameters[*].name',
+          '$.paths[*][get,put,post,delete,options,head,patch,trace].parameters[*].name',
+        ],
       then: {
-        function: undefined,
+        function: pattern,
+          functionOptions: {
```
Comment (P0lip) [inline src/ruleset.ts:724]:
```suggestion
        functionOptions: {
```
